class TestLocalMetadataStore:
    def test_init_run(self):
        ...

    def test_log_metadata(self):
        ...

    def test_check_dst_folder(self):
        ...

    def test_build_source_destination(self):
        ...

    def test_get_run_metadata_uri(self):
        ...
